spring.application.name=ProductFarmMarket
spring.datasource.url=jdbc:postgresql://db:5432/productfarmmarket
spring.datasource.username=marketplace_user
spring.datasource.password=marketplace
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JWT Configuration ---
# ????????? ???? (??????? 32 ??????? ??? ???????)
application.security.jwt.secret-key=aVerySecureKeyThatIsAtLeast32CharactersLongForYourProject12345
# ?????? ??? ?????? (24 ?????? ? ????????????)
application.security.jwt.expiration=86400000