version: '3.8'

services:

  db:
    # Використовуємо конкретну стабільну версію для надійності
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: productfarmmarket
      POSTGRES_PASSWORD: marketplace
      POSTGRES_USER: marketplace_user
    volumes:
      # Змінюємо ім'я volume для уникнення конфлікту зі старими даними
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend-spring
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # URL залишається коректним: jdbc:postgresql://<service_name>:<port>/<db_name>
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productfarmmarket
      SPRING_DATASOURCE_USERNAME: marketplace_user
      SPRING_DATASOURCE_PASSWORD: marketplace
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      # Мапимо папку uploads у контейнері на папку uploads на вашому комп'ютері
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend-react
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # Оголошення нового volume
  db-data:
